In [4]:
import tensorflow as tf
import numpy as np

x = [0., 1., 2., 3., 4., 5., 6., 7.]
y = tf.reshape(x, [2, 2, 2])



# Use unstack on the 3D matrix with different axis values.
unstack_axis1 = tf.unstack(y, axis=0)

# Use stack to combine tensors.
stack_axis1 = tf.stack(unstack_axis1, axis=0)

# Use unstack on axis value 2.
unstack_axis2 = tf.unstack(y, axis=2)

session = tf.Session()

print("INPUT")
print(session.run(y))
print("UNSTACK AXIS 1")
print(session.run(unstack_axis1))
print('np: ',np.array(session.run(unstack_axis1)))
print('------------')
for i in np.array(session.run(unstack_axis1)):
    print(i)
print('------------')
print("STACK AXIS 1")
print(session.run(stack_axis1))
print("UNSTACK AXIS 2")
print(session.run(unstack_axis2))

INPUT
[[[0. 1.]
  [2. 3.]]

 [[4. 5.]
  [6. 7.]]]
UNSTACK AXIS 1
[array([[0., 1.],
       [2., 3.]], dtype=float32), array([[4., 5.],
       [6., 7.]], dtype=float32)]
np:  [[[0. 1.]
  [2. 3.]]

 [[4. 5.]
  [6. 7.]]]
------------
[[0. 1.]
 [2. 3.]]
[[4. 5.]
 [6. 7.]]
------------
STACK AXIS 1
[[[0. 1.]
  [2. 3.]]

 [[4. 5.]
  [6. 7.]]]
UNSTACK AXIS 2
[array([[0., 2.],
       [4., 6.]], dtype=float32), array([[1., 3.],
       [5., 7.]], dtype=float32)]
